name: 'scp-and-cmd'

description: 'A GitHub Action that send the build file to a remote server for deployment via scp.'

inputs:

  local:
    description: 'Local file path'
    required: true

  remote:
    description: 'Remote file path'
    required: true

  host:
    description: 'Remote server address'
    required: true

  port:
    description: 'Remote server port'
    required: false
    default: 22

  user:
    description: 'Remote server user'
    required: true

  key:
    description: 'Remote server private key'
    required: true

  command:
    description: 'Remote server command'

  precopy:
    description: 'Remote server command, before copy'
runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'upload-cloud'
  color: 'green'
